### PR TITLE
Automatically detect and restart php-fpm

### PR DESCRIPTION
**Pull request by REBELinBLUE**
Continuing #238 - Not sure why github thinks there are no commits

Related to #73 

Not sure about this one anymore... turns out to be so many different ways to do this depending on the server and the version of PHP

/etc/init.d/php-fpm restart
/etc/init.d/php5-fpm restart
/etc/init.d/php7.0-fpm restart

service php-fpm restart
service php5-fpm restart
service php7.0-fpm restart

restart php-fpm
restart php5-fpm
restart php7.0-fpm

systemctl restart php-fpm.service
systemctl restart php5-fpm.service
systemctl restart php7.0-fpm.service
May just leave this for people to have as a custom command themselves

### CODE REVIEW

**Comment by paulocastellano** [comment]
accept it please.

**Comment by REBELinBLUE** [comment]
I never finished it, still needs work

**Comment by axeloz** [comment]
This is an interesting PR because I have the same need. But I don't think that restarting PHP is a good idea. It will lead to more problems that it will fix things. As @REBELinBLUE said (or wrote), if PHP refuses to start again, this will impact ALL websites hosted on this server, not only the current deployed project. And even if it starts, that will break any running requests and lead to 5xx errors for some visitors.

Plus, the problem is not related to php-fpm itself but is due to opcache. So my guess would be to clear opcache's cache when applicable.

**Comment by REBELinBLUE** [comment]
Yeah I decided I wasn't sure it was best to do it automatically but people can just add the command themselves as after install if they want to do it, plus there are different ways of doing it

**Pull request closed without merging**
