### PR TITLE
Access control lists/User levels

### PR DESCRIPTION
**Pull request by REBELinBLUE**
Continuing #236 - Not sure why github has decided there are no commits

### CODE REVIEW

**Comment by axeloz** [comment]
Holy moly! I was working on this today for my personal needs. I wanted to end this feature and send a pull request. 
I think I used a different approach with two levels:
* a user can be superadmin or not: has access to the admin panel and all projects
* a project can have one or many users attached to it with two roles: admin and user. The user can only see the project details, the deployment list and start a new deployment. 

About this, I'm not sure how to scaffold the front-end. I understand this is a different repository but where did you clone it? Inside the main repo? Where it is building? 
Thanks

Axel

**Comment by REBELinBLUE** [comment]
I clone it into a separate directory, then to build it run `DEPLOYER_DIR=~/Workspace/deployer make build`

The idea was to completely separate the UI logic and rebuild the frontend as a SPA using Vue or React; but as with everything else work has gotten in the way the last year so I haven't had much of a chance

**Comment by REBELinBLUE** [comment]
To be honest I think your idea is a good starting point

**Comment by axeloz** [comment]
Ok, let me try to move further on my feature. You will tell me what you think about it...

**Comment by axeloz** [comment]
Well, I have started to push: https://github.com/axeloz/deployer/tree/feature/user-roles
This includes: 
* the db migrations
* the AuthServiceProvider
* the Policies
* the @can on the project details view
* the "users" tab on the admin project creation and edition view
* the "super admin" field on the admin user creation and edition view
* the "super admin" column on the admin users listing

Now I must touch the frontend. As soon as I build, the front breaks. 
```
TypeError: i.default(...).autocomplete is not a function[En savoir plus] app.js:1:1307763
```
Any idea ?
Thanks

**Comment by REBELinBLUE** [comment]
Are you using a separate branch from the frontend? Can't seem to see any changes on your copy of the repository.

If I use your copy of both repositories it seems to work fine for me, however I have only tested the frontend build process on node v9.3.0 (see the `.nvmrc` file) so maybe it is something to do with that if you are using a different version?

**Comment by axeloz** [comment]
Hum, I'm using the master of deployer that I branched on my fork. And I'm using the master of deployer-frontend that I cloned directly next to the deployer repo.  
Then I issued a `DEPLOYER_DIR=../deployer/ make build`

```
vagrant@vagrant:/vagrant/www/deployer-frontend$ node -v
v10.4.0
```

```
vagrant@vagrant:/vagrant/www/deployer-frontend$ npm -v
6.1.0
```

Thanks

**Comment by REBELinBLUE** [comment]
Did npm install actually work? On node 10.4.0 it fails badly for me 
[output.log](https://github.com/REBELinBLUE/deployer/files/2101521/output.log)

**Comment by axeloz** [comment]
It works when commenting the following block into views/Server.js

```
$(`#${element} #${element}_name`).autocomplete({
  serviceUrl: routes.serversAutocomplete,
  dataType: 'json',
  noCache: true,
  preserveInput: true,
  transformResult: response => ({
    suggestions: $.map(response.suggestions, dataItem => ({
      value: `${dataItem.name} (${dataItem.user}@${dataItem.ip_address})`,
      data: dataItem,
    })),
  }),
  onSelect: (suggestion) => {
    fields.forEach((field) => {
      $(`#${element}_${field}`).val(suggestion.data[field]);
    });

    $(`#${element}_deploy_code`).prop('checked', suggestion.data.deploy_code);
  },
});
```

**Comment by axeloz** [comment]
Hello @REBELinBLUE,

I just pushed again on my branch (https://github.com/axeloz/deployer/tree/feature/user-roles). 
Now project modal is working with the "users" tab. It displays the current project's users. And it saves properly the users. 

What is missing: 
* autocomplete on the project modal users tab: I'm trying to setup Typeahead
* I must test to deploy as regular user to make sure it still works.
* fix the issue I talked about just above where I had to comment some code to make the front work

Can you have a look and tell me what you think so far?
Thanks

Axel

**Comment by axeloz** [comment]
@REBELinBLUE I'm nearly there! I'm just a little bit stuck on Backbone (I'm not not an expert). As you can see on the screenshot below, I split managers and users. Autocomplete works but with fake data. I manage to create the user collection into the view. But I have no idea how to load this collection into the project's view...
How should I commit the changes in the deployer-frontend to show you ? 
Thanks


capture d ecran 2018-06-15 a 15 41 46

**Comment by REBELinBLUE** [comment]
Sorry, I've been a combination of busy then sick the last 5 evenings, I will take a look when I get home from work today. Screenshot looks good!

**Comment by axeloz** [comment]
@REBELinBLUE no worries. Thanks, let me know. 

That upsets me to get stuck on the last 5% :( I'll try to figure it out anyways...

**Comment by REBELinBLUE** [comment]
https://en.wikipedia.org/wiki/Ninety-ninety_rule ;)

**Comment by axeloz** [comment]
I didn't know about this, very fun and so pertinent ;)

**Comment by REBELinBLUE** [comment]
OK got it running so I am taking a look now.

First thing `database/seeds/UserTableSeeder.php` you need to set the admin user to have the correct role, similarly with `app/Console/Commands/InstallApp.php` in the `createAdminUser` otherwise on initial install there is no admin user.

**Comment by REBELinBLUE** [comment]
It might be easier to create a proper pull request rather than discussing it here, and I'll close this

**Comment by REBELinBLUE** [comment]
The assets silently fail to build, when running in verbose mode you see `npm verb lifecycle deployer-frontend@0.0.1~development: unsafe-perm in lifecycle true`.

After some investigation, it looks like it is because on line 58 of `webpack.mix.js` you've added `${paths.typeahead}/style.css` but `typeahead` is not defined in the paths array and there is nothing in the package.json about it?

**Comment by REBELinBLUE** [comment]
Actually, turns out that is not why build is failing, it is because npm doesn't allow access to ../ which you've changed the build path to include (I guess yarn does). So I have it building now

**Comment by REBELinBLUE** [comment]
So this is where it gets confusing.

If I revert the `package-lock.json` then run `npm install --save bootstrap-tagsinput` then the server autocomplete works correctly, it is only if I remove the `package-lock.json` and install again (or use yarn install) that it starts failing. That means there is some minor version of a package which is causing the problem

**Comment by axeloz** [comment]
Thanks for your feedbacks. I'll try to answer everything: 
* yes I did change the `const build = '../deployer/public';` setting into the webpack.config in order to be able to use `yarn run watch`. It's very convenient but I did commit this by mistake. 
* OK for the Seeds. I will add it
* OK for the pull request. I will do it
* You are right about the `${paths.typeahead}`. I couldn't make it work so I used a different library that I directly included into the views/admin/Projects.js view `require('../../utils/boostrap3-typeahead.min.js');`. Not very clean, I'll try to improve this before creating my pull request.
* I'll check the NPM thing


Thanks

**Comment by REBELinBLUE** [comment]
Closing this

**Pull request closed without merging**
