### PR TITLE
[Feature] Server Manager

### PR DESCRIPTION
**Pull request by cfpinto**
Please prefix your pull request with one of the following: **[FEATURE]** **[FIX]** **[IMPROVEMENT]**.

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/REBELinBLUE/deployer/blob/master/.github/CONTRIBUTING.md)?
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [ ] Do the TravisCI tests pass?
- [ ] Does the StyleCI test pass?

_NOTE: The last 2 are not required to open a PR and can be done afterwards /
while the PR is open._

---

### Description of change

Gives the user the possibility to store server templates that can them be used in the Project pane.

Integration and unit tests pass

### CODE REVIEW

**Comment by REBELinBLUE** [comment]
👍 Thanks, busy today but I shall review it tomorrow

**Comment by REBELinBLUE** [comment]
Apologies for the delay, I have been out of the country without access to a computer. I am back now so I will endeavour to get this merged either today or tomorrow

**Comment by REBELinBLUE** [comment]
Sorry for the delay on this, I've been a lot busier than I expected. Looking at it now

**Comment by cfpinto** [comment]
No worries, been quite busy myself.

**Pull request merged**
