### PR TITLE
Feature/tabs hashes

### PR DESCRIPTION
**Pull request by axeloz**
When switching tab on the projet's page, a hash is now added to the URL. This hash is detected but the page is reloaded and the correct tab is shown.

### CODE REVIEW

**Comment by REBELinBLUE** [comment]
Can you rebase with master please?

**Comment by axeloz** [comment]
Sorry, I did not get time to apply the changes on the templates level. And then I forgot about it.

**Comment by REBELinBLUE** [comment]
No worries

**Comment by axeloz** [comment]
Same as deployer-frontend, I synched from upstream and rebased. Is that ok ?

**Pull request closed without merging**
