### PR TITLE
[FIX] Slack webhook format check

### PR DESCRIPTION
**Pull request by axeloz**
**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [contributing guidelines](https://github.com/REBElinBLUE/deployer/.github/CONTRIBUTING.md)?
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [ ] Do the TravisCI tests pass?
- [ ] Does the StyleCI test pass?

---

### Description of change

We are currently migrating from Slack to Rocket.chat in order to host our data. Rocket.chat webhooks are 100% compatible with Slach webhooks but cannot be used on Deployer as the request is checking the webhook URL format that must match Slack format.
Removing this check and replacing it with a simple URL check should allow anyone to use webhooks for Rocket chat too.

### CODE REVIEW

**Comment by axeloz** [comment]
Oops why are there 4 files changed in my PR? I just changed one file only, sorry, I probably missed something.

**Comment by REBELinBLUE** [comment]
Hmm, weird not sure what happened there. Try a completely new branch, or I can just make the change myself since it is simple. Never heard of rocket.chat, will have to look myself, we use slack at work but only the free version as the enterprise license is ridiculous and we have 700+ users 😂

**Comment by axeloz** [comment]
The IT team decided to ban Slack from work. That's why I have installed my own instance of Rocket.chat which is a perfect clone. 

I redid the branch new pull request, working now...

**Comment by REBELinBLUE** [comment]
Merged

**Comment by axeloz** [comment]
Thanks

**Pull request closed without merging**
