### PR TITLE
Finish the feature that user manage it's self profile

### PR DESCRIPTION
**Pull request by iflamed**
Now it's support below feature:
1. Change name.
2. Change the login email.
3. Change the password.
4. Change the avatar.

Example:
image

### CODE REVIEW

**Comment by REBELinBLUE** [comment]
Awesome, that is much more detailed than I was going to do. Will get it merged in later today

**Comment by iflamed** [comment]
Thanks.

**Comment by REBELinBLUE** [comment]
Sorry for the delay, will hopefully get it merged in at the weekend. Few minor tweaks I want to make

**Comment by iflamed** [comment]
OK，Tweak it what you want！This weekend i will keep updating some feature,

发自 刘兵 的 iPhone

**Comment by REBELinBLUE** [comment]
Sorry for the massive delay on this, been a really busy 6 weeks.

I have made my own branch and am making a few tweaks and then will merge it in later today. Feel free to delete your branch.

Thanks

**Comment by iflamed** [comment]
@REBELinBLUE  Thanks, Let's continue make it much more better.

**Comment by REBELinBLUE** [comment]
👍@iflamed mostly just a few language changes, although I am also adding a button to reset to using gravatar if you have uploaded an avatar

**Pull request closed without merging**
