### PR TITLE
[FEATURE] Ansible example

### PR DESCRIPTION
**Pull request by jcornide**
**In raising this pull request, I confirm the following (please check boxes):**

- [X] I have read and understood the [contributing guidelines](/.github/CONTRIBUTING.md)?
- [X] I have checked that another pull request for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.

_NOTE: The last 2 are not required to open a PR and can be done afterwards /
while the PR is open._

---

### Description of change

Adding a Ansible example to set up a a server and install the deployer tool automatically

### CODE REVIEW

**Comment by REBELinBLUE** [comment]
One minor issue, having an `APP_KEY` hard coded in a secret issue

**Comment by jcornide** [comment]
Hi,

you're right, what would be it a good option? leave it blank and provide instructions on how to add the key?

**Comment by REBELinBLUE** [comment]
If you run `php artisan key:generate` it will set the `APP_KEY`. 

The `JWT_SECRET` should also be generated with `php artisan jwt:generate`

**Comment by jcornide** [comment]
And when I should run those commands? I mean, in what order here? Before clear-compiled? or afterwards?
```
- name: Run scripts to complete deployer installation
  shell: "{{item}}"
  args:
    chdir: "{{deployer_directory}}"
  with_items:
  - "php artisan clear-compiled"
  - "php artisan cache:clear"
  - "php artisan route:clear"
  - "php artisan config:clear"
  - "php artisan view:clear"
  - "php artisan optimize --force"
  - "php artisan config:cache"
  - "php artisan route:cache"
  - "php artisan migrate --force"
  - "npm install --production"
```

**Comment by REBELinBLUE** [comment]
Before the `php artisan config:cache`

**Comment by jcornide** [comment]
done!

**Comment by REBELinBLUE** [comment]
Sorry, could you rebase this with master and I will get it merged

**Comment by jcornide** [comment]
sorry, im not sure what you mean. You want me to merge "ansible_example"
branch changes into my master branch?

On Tue, Mar 22, 2016 at 10:01 PM, Stephen Ball <notifications@github.com>
wrote:

> Sorry, could you rebase this with master and I will get it merged
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/REBELinBLUE/deployer/pull/190#issuecomment-200023807>
>



-- 
José Cornide
Tlf.: 609 720 220

**Comment by REBELinBLUE** [comment]
"This branch is out-of-date with the base branch
Merge the latest changes from master into this branch."

Basically you need to sync your fork https://help.github.com/articles/syncing-a-fork/ && https://help.github.com/articles/merging-an-upstream-repository-into-your-fork/

and merge the changes from master into the branch, or better rebase the changes into master (git rebase master instead of git merge master)

**Comment by jcornide** [comment]
i think i got it :)

On Thu, Mar 24, 2016 at 12:49 PM, Stephen Ball <notifications@github.com>
wrote:

> "This branch is out-of-date with the base branch
> Merge the latest changes from master into this branch."
>
> Basically you need to sync your fork
> https://help.github.com/articles/syncing-a-fork/ &&
> https://help.github.com/articles/merging-an-upstream-repository-into-your-fork/
>
> and merge the changes from master into the branch, or better rebase the
> changes into master (git rebase master instead of git merge master)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/REBELinBLUE/deployer/pull/190#issuecomment-200802224>
>



-- 
José Cornide
Tlf.: 609 720 220

**Comment by REBELinBLUE** [comment]
Have you had a chance to rebase so I can merge it?

**Comment by jcornide** [comment]
Hi Stephen, yes I did and I pushed it, is not ok?

On Fri, Apr 15, 2016 at 10:43 AM, Stephen Ball <notifications@github.com>
wrote:

> Have you had a chance to rebase so I can merge it?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/REBELinBLUE/deployer/pull/190#issuecomment-210364301>
>



-- 
José Cornide
Tlf.: 609 720 220

**Comment by REBELinBLUE** [comment]
Hmm, sorry, would you mind doing it again? I must have missed it and now it is out of date again, I tried merging manually but there where a lot of conflicts (which doesn't really make much sense to me) so thought it safer for you to do it

**Pull request merged**
