### PR TITLE
[FEATURE] Add Chinese language

### PR DESCRIPTION
**Pull request by aiddroid**
### add chinese language

*add chinese language.*

### CODE REVIEW

**Comment by REBELinBLUE** [comment]
Hi

Thanks, awesome! Would you be able to rebase as I have updated master to Laravel 5.3 now so there are a couple of conflicts. Thanks

**Comment by REBELinBLUE** [comment]
Thanks, I shall take a look tomorrow evening :)

**Comment by REBELinBLUE** [comment]
Thanks, I've now added the ability to select your language from your settings 5212f54292d47b3c3e2cd4c62008b4d72b502256

**Comment by aiddroid** [comment]
Thanks

**Comment by REBELinBLUE** [comment]
The new notifications feature in `master` has quote a few new strings, if you want to translate them you can run the following commands to see what is missing

```shell
$ php artisan langman:show channels
$ php artisan langman:show checkUrls
$ php artisan langman:show deployments
$ php artisan langman:show emails
$ php artisan langman:show heartbeats
$ php artisan langman:show notifications
$ php artisan langman:show users
```

**Pull request merged**
