### PR TITLE
Log error output of processes that did not run successfully

### PR DESCRIPTION
**Pull request by emielmolenaar**
**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/REBELinBLUE/deployer/blob/master/.github/CONTRIBUTING.md)?
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [ ] Do the TravisCI tests pass?
- [ ] Does the StyleCI test pass?

---

If process fails to run successfully, log the error output.

In my case, Deployer did not have access to a git submodule of a deployed project. A deployment then fails without any error output and all the deployment steps are set to "cancelled". It took me a while before I discovered this, and a some extra lines of logging would have helped me. I guess this is useful in a lot of other cases too :smile:

### CODE REVIEW

**Comment by emielmolenaar** [comment]
Hmm, I will fix the tests.

**Comment by REBELinBLUE** [comment]
Good idea, can't believe I had not thought of doing that

**Comment by emielmolenaar** [comment]
Too busy. Will try to make some time this week :hourglass_flowing_sand:

**Comment by emielmolenaar** [comment]
Thanks for merging. Any point-in-the-right direction on how to write a nice test to test a failing process?

**Comment by REBELinBLUE** [comment]
I went ahead and did it https://github.com/REBELinBLUE/deployer/blob/771c7ebdc3d6b7797fcc81e52172835373300fb3/tests/Unit/Services/Scripts/RunnerTest.php#L245

**Comment by emielmolenaar** [comment]
Awesome!

**Pull request merged**
