### PR TITLE
FIX fixing ssh connection issues

### PR DESCRIPTION
**Pull request by jlaso**
Please prefix your pull request with one of the following: **[FEATURE]** **[FIX]** **[IMPROVEMENT]**.

**In raising this pull request, I confirm the following (please check boxes):**

- [X] I have read and understood the [contributing guidelines](https://github.com/REBElinBLUE/deployer/.github/CONTRIBUTING.md)?
- [X] I have checked that another pull request for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [ ] Do the TravisCI tests pass?
- [ ] Does the StyleCI test pass?

_NOTE: The last 2 are not required to open a PR and can be done afterwards /
while the PR is open._

---

### Description of change

*Please provide a description of the change here.*

trying to reproduce the error that doesn't let me to set my server on the project panel, I looked into the log stored in storage/app/XXXX.log and I got this message

[2016-11-08 12:26:51] production.DEBUG: ssh -o CheckHostIP=no \
    -o IdentitiesOnly=yes \
    -o StrictHostKeyChecking=no \
    -o PasswordAuthentication=no \
    -o IdentityFile=/var/projects/deployer/storage/app/sshkeyOZD8Nj \
    -p 22 XXXXXX@XXXXXX 'bash -s' << 'EOF'  etc ...

NOTE:
the file sshkey???? is removed by deployer inmediately but I just trick it filling in with the private_key field on the DB for the current project

Executing the same command by hand I got:

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 0644 for '/var/projects/deployer/storage/app/sshkeyOZD8Nj' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
bad permissions: ignore key: /var/projects/deployer/storage/app/sshkeyOZD8Nj

whith my change we ensure that the privatekey gots the proper permissions

right now with this change I passed the server check and I am able to deploy

### CODE REVIEW

**Comment by REBELinBLUE** [comment]
Thanks, I shall take a look at this

**Comment by REBELinBLUE** [comment]
Just noticed this is pointing at the wrong branch, can you open a new PR for merging into master?

**Comment by jlaso** [comment]
Seems that is not working my fix in a production environment. For any reason when the process is launched is using another user and I cannot debug the process by hand. I will come later with the solution if any. 

Sorry to bother you ;)

**Comment by REBELinBLUE** [comment]
Hmm, the script which creates the SSH key should be running as the same user as the process which uses it, they are after all bother launched by the Laravel queue daemon which is run by supervisor :|

**Pull request closed without merging**
